<?php
//    AlertTweets.php
//
//    arpsc_tweets displays the mi_arpsc twitter timeline inside
//    a normal mi-arpsc frame.  The timeline is generated by some
//    javascript provided by twitter.
//
    include('includes/session.inc');
    $title=_('Homeland Security Alerts');

    include('includes/functions.inc');

    // Remember the launch time
    $starttime = strftime("%A, %B %d %Y, %H:%M");

    // Open the database
    $db = mysql_connect($host , $dbuser, $dbpassword);
    mysql_select_db($DatabaseName,$db);

    NTSheader($title,"ARES RACES ARPSC Michigan Section Twitter");

    leftBar( $db );
?>
  <div id="main">
<center>
    <h1>Homeland Security Alerts</h1>

<script src="http://widgets.twimg.com/j/2/widget.js"></script>
<script>
new TWTR.Widget({
  version: 2,
  type: 'list',
  rpp: 1,
  interval: 6000,
  title: 'NTASAlerts',
  subject: 'Recent DHS Alerts',
  width: 450,
  height: 100,
  theme: {
    shell: {
      background: '#000080',
      color: '#ffffff'
    },
    tweets: {
      background: '#600000',
      color: '#ffffff',
      links: '#ccccff'
    }
  },
  features: {
    scrollbar: true,
    loop: false,
    live: true,
    hashtags: true,
    timestamp: true,
    avatars: true,
    behavior: 'all'
  }
}).render().setList('NTASAlerts', '').start();
</script>
<p>&nbsp;</p>
<h1>EMHSD</h1>

      <script src="http://widgets.twimg.com/j/2/widget.js"></script>
      <script>
      new TWTR.Widget({
	version: 2,
	type: 'profile',
	rpp: 8,
	interval: 6000,
	title: 'Michigan State Police',
	subject: 'EMHSD',
	width: 450,
	height: 200,
      theme: {
	shell: {
	  background: '#000077',
	  color: '#ffff00'
	   },
	   tweets: {
	   background: '#eeeeee',
	   color: '#000000',
	   links: '#000077'
	   }
	 },
       features: {
	scrollbar: false,
	loop: false,
	live: true,
	hashtags: true,
	timestamp: true,
	avatars: true,
	behavior: 'all'
       }
    }).render().setUser('MichEMHS').start();
      </script>

<p>&nbsp;</p>
<h1>Ready dot gov</h1>

      <script src="http://widgets.twimg.com/j/2/widget.js"></script>
      <script>
      new TWTR.Widget({
	version: 2,
	type: 'profile',
	rpp: 8,
	interval: 6000,
	title: 'ready dot gov',
	subject: 'Ready dot gov',
	width: 450,
	height: 200,
      theme: {
	shell: {
	  background: '#000077',
	  color: '#ffff00'
	   },
	   tweets: {
	   background: '#eeeeff',
	   color: '#000000',
	   links: '#000077'
	   }
	 },
       features: {
	scrollbar: false,
	loop: false,
	live: true,
	hashtags: true,
	timestamp: true,
	avatars: true,
	behavior: 'all'
       }
    }).render().setUser('ReadydotGov').start();
      </script>


<p>&nbsp;</p>
<h1>Shakeout</h1>

      <script src="http://widgets.twimg.com/j/2/widget.js"></script>
      <script>
      new TWTR.Widget({
	version: 2,
	type: 'profile',
	rpp: 8,
	interval: 6000,
	title: 'Central U.S. Shakeout',
	subject: 'National Level Exercise',
	width: 450,
	height: 200,
      theme: {
	shell: {
	  background: '#000077',
	  color: '#ffff00'
	   },
	   tweets: {
	   background: '#ffffff',
	   color: '#000000',
	   links: '#000077'
	   }
	 },
       features: {
	scrollbar: false,
	loop: false,
	live: true,
	hashtags: true,
	timestamp: true,
	avatars: true,
	behavior: 'all'
       }
    }).render().setUser('CentUS_ShakeOut').start();
      </script>

      <p>&nbsp;</p>
      </center>

  </div>
<?php
    sectLeaders($db);
    footer($starttime,$maxdate,
      "\$Revision: 1.1 $ - \$Date: 2011-04-25 08:57:14-05 $");
?>
</div>
</body>
</html>
